Add ListItemArticle
GetLuko/streamline pull request #67
Opened 2023-05-12 12:47 UTC by ludwig-pro

## Checklist before requesting a review
- [ ] Working on iOS
- [ ] Working on Android
- [ ] Integration tests added
- [ ] Visual regressions screenshots are up to date
- [ ] Design validated

2023-05-12 12:48 UTC, ludwig-pro commented
question in progress : https://www.figma.com/file/tOJLNigXQXJqCSKgJFPZn5?node-id=4253:7007#442962482

2023-05-15 09:29 UTC, ianrobertlambert commented
It looks great @ludwig-pro, thanks! I checked both iOS and Android.

### Feedback
- [ ] Can we please change the chevron color to `Grey-400`?
- [ ] Can we please use a `Primary` spinner on this ListItem? It should be the Bluko version.
- [ ] Is it possible to use a `MD` spinner here (24x24)? I know it is larger than the chevron icon, but is there a way to do this by adjusting the padding maybe?

### Notes
- Based on your Slack message last week, I’ve created additional states inside Figma. Would it be possible to add the other state please? We now have:
  - [X] Default
  - [X] Touch
  - [ ] Disabled
  - [X] Loading
  - [X] Skeleton
- I can create a separate ticket if this was not part of the original scope?

2023-05-15 10:11 UTC, kimak requested changes

2023-05-15 10:11 UTC, kimak commented on packages/streamline/src/components/list-items/list-item-article/list-item-article.spec.tsx
> +    await waitFor(() => expect(onPress).toHaveBeenCalledTimes(1));
missing tests case:

- getByText('Title')
- getByText('Description')

And imageSource using accessibility text?

2023-05-15 12:58 UTC, ludwig-pro commented
> * is there a way to do this by adjusting the padding maybe?

I'm not sure to understand what you want 🤔 @ianrobertlambert

2023-05-15 13:03 UTC, ludwig-pro commented
latest screenshot 

![Simulator Screen Shot - iPhone 12 - 2023-05-15 at 15 03 09](https://github.com/GetLuko/streamline/assets/62896243/690a04ce-0b5f-4343-944f-26c4f2e9db24)

2023-05-15 13:18 UTC, ianrobertlambert commented
> > * is there a way to do this by adjusting the padding maybe?
> 
> I'm not sure to understand what you want 🤔 @ianrobertlambert

@ludwig-pro these look great, thanks a lot! ✨

If we look at this screenshot:

<img width="866" alt="image" src="https://github.com/GetLuko/streamline/assets/34472045/8f3d24db-cff4-44ea-9280-62fbe29dccb9">

Sorry if I wasn't clear earlier. The `ChevronFarRight` icon is 16px x 16px, while the `MD Spinner` is 24px x 24px. How did you adjust the size difference between the two states? Did you decrease the space between the text and the area on the right side by -8px to accommodate the larger size of the spinner? I'm just trying to better understand how you built it. 😊

![image](https://github.com/GetLuko/streamline/assets/34472045/28dfe925-cb5d-431a-9c1b-8fe000f4cea4)

2023-05-15 13:54 UTC, ludwig-pro commented
my global container have a padding, 

then I have a vertical stack with a <image> and a <text + icon> where <text + icon> have a padding left

and finally I have a vertical stack for the <text> and <the icon> when the text have a flex 1 ( so it's grow to fullfilled ) and the icon have a padding left

![image](https://github.com/GetLuko/streamline/assets/62896243/b3a397a4-86fc-4f03-93a1-d03af14be1d6)

2023-05-23 09:13 UTC, hcourthias approved these changes

2023-05-23 09:13 UTC, hcourthias commented on packages/streamline/src/components/list-items/list-item-article/components/image-spinner.tsx
> + * https://github.com/FormidableLabs/react-native-ama/issues/92
Unrelated comment ?

2023-05-23 10:21 UTC, ludwig-pro commented on packages/streamline/src/components/list-items/list-item-article/components/image-spinner.tsx
> + * https://github.com/FormidableLabs/react-native-ama/issues/92
👀 thanks

2023-05-23 10:26 UTC, kimak approved these changes

2023-05-23 10:26 UTC, merged