Hugo/feat/dialog
GetLuko/streamline pull request #70
Opened 2023-05-16 14:59 UTC by hcourthias

## Checklist before requesting a review
- [ ] Working on iOS
- [ ] Working on Android
- [ ] Integration tests added
- [ ] Visual regressions screenshots are up to date
- [ ] Design validated

2023-05-16 15:07 UTC, hcourthias commented on packages/sandbox/e2e/ios/screenshots/Dialog.png
@ianrobertlambert The margin around the modal will not be their when using the component in the main project.

2023-05-17 08:37 UTC, judastheo requested changes
Nice!

2023-05-17 08:37 UTC, judastheo commented on packages/streamline/src/components/dialog/dialog.tsx
> +        style={{ marginBottom: insets.bottom }}
You can move this style and the `useSafeAreaInsets` in the `useStyles` part

2023-05-17 08:37 UTC, judastheo commented on packages/streamline/src/components/dialog/dialog.tsx
> +      ...(buttons.orientation === 'horizontal'
You check 3 times in the file `buttons.orientation === 'horizontal'`, you could have only one `isHorizontal` const.

2023-05-17 08:37 UTC, judastheo commented on packages/streamline/src/components/dialog/dialog.types.tsx
> +      appearance: 'neutral' | 'secondary';
@hcourthias @ianrobertlambert Better safe than sorry, make sure you're aligned on possible appearance for each button.

2023-05-17 08:37 UTC, judastheo commented on packages/streamline/src/primitives/icon/icon.constants.ts
> +  xlarge: 48,
Discussed with @hcourthias , we may change it later but for now, it's just to match the icon different possibilities but should be of no use.

2023-05-17 16:53 UTC, judastheo approved these changes

2023-05-22 08:04 UTC, merged

2023-05-30 16:15 UTC, ianrobertlambert commented
Thanks @hcourthias - It's looking good! ✨ I have some questions and small feedback hopefully:

- [ ] The text content should be centered when the dialog uses an an icon.
- [ ] Does the `Bold` typography use a different typeface? I noticed that it was different on the screenshots, but not on the Expo environment? Is this issue specific to the `Dialog` component or is it a general `Typography` issue?
- [ ] Is there a way to test these in an overlay setting? It might provide a more accurate representation of their behavior on iOS/Android.
- [ ] Just to confirm, is the button(s) positioned 16px away from the edge of the `HomeIndicator` container on iOS/Android?
![image](https://github.com/GetLuko/streamline/assets/34472045/6eb4df60-481c-44f8-894e-24a0af48954b)