feat: create InputDatePicker component
GetLuko/streamline pull request #82
Opened 2023-06-07 21:08 UTC by kimak

## Checklist before requesting a review
- [x] Working on iOS
- [x] Working on Android
- [x] Integration tests added
- [ ] Visual regressions screenshots are up to date
- [ ] Design validated

2023-06-08 07:23 UTC, hcourthias requested changes

2023-06-08 07:23 UTC, hcourthias commented on packages/streamline/src/components/input-date-picker/input-date-picker.tsx
> +const ModalPickerIOS = ({
Could you extract this component to another file ?

2023-06-08 07:23 UTC, hcourthias commented on packages/streamline/src/components/input-date-picker/input-date-picker.tsx
> +      style={{ flex: 1 }}
Avoid inline style

2023-06-08 07:23 UTC, hcourthias commented on packages/streamline/src/components/input-date-picker/input-date-picker.tsx
> +        style={{ height: 400 }}
Same here, Avoid inline style

2023-06-09 08:19 UTC, kimak commented on packages/sandbox/e2e/ios/screenshots/InputDatePicker.png
@ianrobertlambert to review on iOS

2023-06-09 08:19 UTC, kimak commented on packages/sandbox/e2e/android/screenshots/InputDatePicker.png
@ianrobertlambert to review on Android

2023-06-09 09:34 UTC, judastheo approved these changes

2023-06-09 09:38 UTC, hcourthias approved these changes

2023-06-12 07:57 UTC, merged

2023-06-13 09:20 UTC, ianrobertlambert commented
Thanks @kimak ! Sorry for my late reply on this.
Reviewed! Both iOS and Android are working well. 😊✨

- Can we please update the blue colors on both iOS and Android to match our Bluko brand color?
Bluko-500: `#2D50E6`

- Just so I better understand... Are we using a "library" for this? Will this mean we can stay aligned with the native behavior if the native picker on iOS/Android changes?

2023-06-13 13:21 UTC, kimak commented
> Thanks @kimak ! Sorry for my late reply on this. Reviewed! Both iOS and Android are working well. 😊✨
> 
> * Can we please update the blue colors on both iOS and Android to match our Bluko brand color?
>   Bluko-500: `#2D50E6`

I updated it for iOS here: https://github.com/GetLuko/streamline/pull/85#discussion_r1228115074

On Android, I'm limited with expo the solution we use here for the sandbox
https://expo.canny.io/feature-requests/p/customize-android-apptheme

But it will be good once integrated with the final app:

![Screenshot_20230613-145523_Staging ](https://github.com/GetLuko/streamline/assets/1573707/8a8ab5dc-19c3-4f2f-ad79-d612a16acf93)


> * Just so I better understand... Are we using a "library" for this? Will this mean we can stay aligned with the native behavior if the native picker on iOS/Android changes?

Yes, it's a react-native library https://github.com/react-native-datetimepicker/datetimepicker using Native implementation.
It will be retro compatible with new OS versions. With that being said, sometime we still need update the lib to be up to date with the latest OS (last time was iOS 14 for example).

2023-06-14 07:02 UTC, ianrobertlambert commented
Thanks for the clarity! Sounds good. 👍