add input number component
GetLuko/streamline pull request #83
Opened 2023-06-09 07:40 UTC by hcourthias

## Checklist before requesting a review
- [ ] Working on iOS
- [ ] Working on Android
- [ ] Integration tests added
- [ ] Visual regressions screenshots are up to date
- [ ] Design validated

2023-06-12 13:58 UTC, kimak requested changes

2023-06-12 13:58 UTC, kimak commented on packages/streamline/src/components/inputs/input-code/components/cell.tsx
> +      {...(index !== length - 1 ? { marginRight: 'xs' } : {})}
```suggestion
      marginRight={lastIndex ? undefined : 'xs'} 
```
WDYT?

2023-06-12 13:58 UTC, kimak commented on packages/streamline/src/components/inputs/input-code/input-code.tsx
> +  testID = 'input-code',
Avoid default testID as an ID should be unique

2023-06-13 07:49 UTC, ianrobertlambert commented
Looks good from my side! Thanks @hcourthias 😊

2023-06-22 06:27 UTC, judastheo approved these changes

2023-06-29 12:51 UTC, judastheo approved these changes

2023-06-29 13:03 UTC, merged